### ISSUE TITLE
score png

### ISSUE THREAD

**Issue by repinek** [takkun-mint/FallGuysTools#1]
Fix pls score.png, quality is very bad and no shadows

**Comment by repinek** [comment]
![Score](https://github.com/takkun-mint/FallGuysTools/assets/137826826/3db9ad4f-489e-4b67-89e3-2a1e2c67d8aa)

**Comment by takkun-mint** [comment]
Thank you for contacting us.
We have replaced the Score.png image.
Please let me know if there is anything else I can do.

**Comment by repinek** [comment]
thank!
