### ISSUE TITLE
Tile revival speed

### ISSUE THREAD

**Issue by repinek** [takkun-mint/FallGuysTools#2]
i guess tile revival speed doesnt working? i played 3 minutes and tile revival doesnt changes

![image](https://github.com/takkun-mint/FallGuysTools/assets/137826826/91e60bf9-5904-4630-8b19-97d909c8cf20)

**Comment by repinek** [comment]
by the way i have suggestions about other languages in your program

**Comment by takkun-mint** [comment]
Thanks for contacting us!
It is possible that the database was corrupted....
We have corrected the database and would appreciate it if you could check to see if it has been fixed.
At the moment, only Japanese and English are supported, but do you want us to support other languages?
It is very difficult to support all languages,
so please let us know if there are any languages you would like to see added.
Thank you for your continued support.

**Comment by repinek** [comment]
> Thanks for contacting us! It is possible that the database was corrupted.... We have corrected the database and would appreciate it if you could check to see if it has been fixed. At the moment, only Japanese and English are supported, but do you want us to support other languages? It is very difficult to support all languages, so please let us know if there are any languages you would like to see added. Thank you for your continued support.

I would like to see Russian, and if you are interested, I could help translate

**Comment by repinek** [comment]
> Thanks for contacting us! It is possible that the database was corrupted.... We have corrected the database and would appreciate it if you could check to see if it has been fixed. At the moment, only Japanese and English are supported, but do you want us to support other languages? It is very difficult to support all languages, so please let us know if there are any languages you would like to see added. Thank you for your continued support.

ok, i will check it. thank!

**Comment by repinek** [comment]
> Thanks for contacting us! It is possible that the database was corrupted.... We have corrected the database and would appreciate it if you could check to see if it has been fixed. At the moment, only Japanese and English are supported, but do you want us to support other languages? It is very difficult to support all languages, so please let us know if there are any languages you would like to see added. Thank you for your continued support.

I am very glad to see Russian in your program, but could you correct some of the text? I used an open source program to get lines from your program (forgive me, but it's much more convenient for me to do it this way), and translated 100% of the text and changed more than 40%, because your translation is bad (I think you used a translator from Japanese to Russian) I hope you accept my edits, I will be glad. the file in which all my translations are attached
[fixed russian localisation fall guys tool.txt](https://github.com/takkun-mint/FallGuysTools/files/13743023/fixed.russian.localisation.fall.guys.tool.txt)

**Comment by repinek** [comment]
anyway, im so happy, because you communicate and take into account what people want 
sorry for my english, using translator

> > Thanks for contacting us! It is possible that the database was corrupted.... We have corrected the database and would appreciate it if you could check to see if it has been fixed. At the moment, only Japanese and English are supported, but do you want us to support other languages? It is very difficult to support all languages, so please let us know if there are any languages you would like to see added. Thank you for your continued support.
> 
> I am very glad to see Russian in your program, but could you correct some of the text? I used an open source program to get strings from your program (forgive me, but it's much more convenient for me to do it this way), and translated 100% of the text and changed more than 40%, because your translation is bad (I think you used a translator from Japanese to Russian) I hope you accept my edits, I will be glad. the file in which all my translations are attached [fixed russian localisation fall guys tool.txt](https://github.com/takkun-mint/FallGuysTools/files/13743023/fixed.russian.localisation.fall.guys.tool.txt)

**Comment by repinek** [comment]
by the way i have a suggestion how you can add nameplate, nickname and name of author map on the creative picture (maybe you know how)

**Comment by takkun-mint** [comment]
> > お問い合わせいただきありがとうございます！  データベースが壊れている可能性があります。データベースを修正しましたので、修正されたかどうかご確認いただけますと幸いです。  現時点では日本語と英語のみ対応していますが、他の言語も対応してほしいですか？  すべての言語をサポートすることは非常に難しいため、追加してほしい言語があればお知らせください。  今後ともよろしくお願いいたします。
> 
> あなたのプログラムにロシア語が登場するのはとてもうれしいですが、テキストの一部を修正してもらえますか? 私はオープンソースプログラムを使用してあなたのプログラムから文字列を取得し（申し訳ありませんが、この方法で行う方がはるかに便利です）、テキストの100％を翻訳し、40％以上を変更しました。あなたの翻訳が悪かったためです（日本語からロシア語への翻訳者を使用したと思います) 私の編集を受け入れていただければ幸いです。 オーバーレイ (場所、ラップなど) の翻訳を忘れないでください。嬉しいです。 私のすべての翻訳が添付されているファイル [ロシア語のローカリゼーションを修正しました Fall Guys Tool.txt ](https://github.com/takkun-mint/FallGuysTools/files/13743023/fixed.russian.localisation.fall.guys.tool.txt)



> > Thanks for contacting us! It is possible that the database was corrupted.... We have corrected the database and would appreciate it if you could check to see if it has been fixed. At the moment, only Japanese and English are supported, but do you want us to support other languages? It is very difficult to support all languages, so please let us know if there are any languages you would like to see added. Thank you for your continued support.
> 
> I am very glad to see Russian in your program, but could you correct some of the text? I used an open source program to get strings from your program (forgive me, but it's much more convenient for me to do it this way), and translated 100% of the text and changed more than 40%, because your translation is bad (I think you used a translator from Japanese to Russian) I hope you accept my edits. Dont forget about translation your overlay (place, laps, etc..) I will be glad. the file in which all my translations are attached [fixed russian localisation fall guys tool.txt](https://github.com/takkun-mint/FallGuysTools/files/13743023/fixed.russian.localisation.fall.guys.tool.txt)

Sorry for the late reply! Thank you for correcting the translation with my internal name! We may not be able to apply it immediately, but we will definitely replace it, so we hope you can wait a little longer!

**Comment by takkun-mint** [comment]
> by the way i have a 2 suggestion, the first one how you can add nameplate, nickname and name of author map on the creative picture (maybe you know how), but I think it's not too safe/good to discuss it here the other one is add a music info to creative round informations (i can send you all localised music ("ingame_music_name:" "name of music")) ![Screenshot_3351](https://private-user-images.githubusercontent.com/137826826/292237670-cf340a85-8e1c-4880-8208-967453f7adc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MjQ0NzEsIm5iZiI6MTcwNTkyNDE3MSwicGF0aCI6Ii8xMzc4MjY4MjYvMjkyMjM3NjcwLWNmMzQwYTg1LThlMWMtNDg4MC04MjA4LTk2NzQ1M2Y3YWRjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQxMTQ5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGIxMTcyZjhhNWIyNzEzMTU1NTQyYWVlOTJhNmIyODk5ODJmMmQxZDU0MDZmOTdiYWRiODg4ZWI3MWEwZWQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G7URQUdjgZ4fOLhLBhSECC_bgW1CFyutLYd-LoDHtcs) ![Screenshot_3350](https://private-user-images.githubusercontent.com/137826826/292237681-f3ed41bd-8bd2-47c3-9796-f798bd41980f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MjQ0NzEsIm5iZiI6MTcwNTkyNDE3MSwicGF0aCI6Ii8xMzc4MjY4MjYvMjkyMjM3NjgxLWYzZWQ0MWJkLThiZDItNDdjMy05Nzk2LWY3OThiZDQxOTgwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQxMTQ5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzYwYTVhYjgyNjBmNmM5ZDc2MTgyZjIwYzZhMzhmZTU4M2VkZTFiMmVmYmM4MjAzMjA1NDg2OTQ0MzFmNjRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Jgs719FFtbxZe1w10sG53aUQHlWyjFBKeNmTzUrvg-k)

Regarding the creative thumbnails and banners,
 it would be very difficult to create from scratch the names of course creators, etc., and I think it would be appropriate to submit this as a management request, not as a Tools item.
Therefore, we are not planning to introduce it at this time! Our apologies! 
We will positively consider adding BGM information in the Creative Course Search Tool!

**Comment by repinek** [comment]
> > by the way i have a 2 suggestion, the first one how you can add nameplate, nickname and name of author map on the creative picture (maybe you know how), but I think it's not too safe/good to discuss it here the other one is add a music info to creative round informations (i can send you all localised music ("ingame_music_name:" "name of music")) ![Screenshot_3351](https://private-user-images.githubusercontent.com/137826826/292237670-cf340a85-8e1c-4880-8208-967453f7adc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MjQ0NzEsIm5iZiI6MTcwNTkyNDE3MSwicGF0aCI6Ii8xMzc4MjY4MjYvMjkyMjM3NjcwLWNmMzQwYTg1LThlMWMtNDg4MC04MjA4LTk2NzQ1M2Y3YWRjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQxMTQ5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGIxMTcyZjhhNWIyNzEzMTU1NTQyYWVlOTJhNmIyODk5ODJmMmQxZDU0MDZmOTdiYWRiODg4ZWI3MWEwZWQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G7URQUdjgZ4fOLhLBhSECC_bgW1CFyutLYd-LoDHtcs) ![Screenshot_3350](https://private-user-images.githubusercontent.com/137826826/292237681-f3ed41bd-8bd2-47c3-9796-f798bd41980f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MjQ0NzEsIm5iZiI6MTcwNTkyNDE3MSwicGF0aCI6Ii8xMzc4MjY4MjYvMjkyMjM3NjgxLWYzZWQ0MWJkLThiZDItNDdjMy05Nzk2LWY3OThiZDQxOTgwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQxMTQ5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzYwYTVhYjgyNjBmNmM5ZDc2MTgyZjIwYzZhMzhmZTU4M2VkZTFiMmVmYmM4MjAzMjA1NDg2OTQ0MzFmNjRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Jgs719FFtbxZe1w10sG53aUQHlWyjFBKeNmTzUrvg-k)
> 
> Regarding the creative thumbnails and banners, it would be very difficult to create from scratch the names of course creators, etc., and I think it would be appropriate to submit this as a management request, not as a Tools item. Therefore, we are not planning to introduce it at this time! Our apologies! We will positively consider adding BGM information in the Creative Course Search Tool!

Well, if anything, you could do this using fgdb information and nameplates pictures with fgdb or pictures files

**Comment by takkun-mint** [comment]
> by the way i have a 2 suggestion, the first one how you can add nameplate, nickname and name of author map on the creative picture (maybe you know how), but I think it's not too safe/good to discuss it here the other one is add a music info to creative round informations (i can send you all localised music ("ingame_music_name:" "name of music")) ![Screenshot_3351](https://private-user-images.githubusercontent.com/137826826/292237670-cf340a85-8e1c-4880-8208-967453f7adc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5OTU0NDQsIm5iZiI6MTcwNzk5NTE0NCwicGF0aCI6Ii8xMzc4MjY4MjYvMjkyMjM3NjcwLWNmMzQwYTg1LThlMWMtNDg4MC04MjA4LTk2NzQ1M2Y3YWRjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQxMTA1NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTU4ZGNiNjA5MDExMGJlOTNhZDNmNzdhM2Q4M2Y0OGJmNGM1Y2RiZTQ1MThiZGNmMTg5YzRlMTE3MzkzNmRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Da1kr1Jg8Z5pMGCXq-YxEQRVSs_Zp4Snhbvdae-xpfU) ![Screenshot_3350](https://private-user-images.githubusercontent.com/137826826/292237681-f3ed41bd-8bd2-47c3-9796-f798bd41980f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5OTU0NDQsIm5iZiI6MTcwNzk5NTE0NCwicGF0aCI6Ii8xMzc4MjY4MjYvMjkyMjM3NjgxLWYzZWQ0MWJkLThiZDItNDdjMy05Nzk2LWY3OThiZDQxOTgwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQxMTA1NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjJjNDNmOWI1ODJmMzQ3ZDEyNzFiZWNmMGM0ODdhMzk3OGNkOTdkMjczYjkwYzc0NTJlOGQ2Y2Q2NjNlYmZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._rQrUPvDCgaspuTz6iOqHvBz403yIVYgYgp95swfmBM)

Added BGM information and other information to the Creative Search Tool!
