### ISSUE TITLE
FallguysToolsを再起動した時にOBSのタイマーに置き換えられてしまう

### ISSUE THREAD

**Issue by ohsakura0** [takkun-mint/FallGuysTools#4]
FallguysToolsを再起動した時に（閉じて再度開く）OBSを起動していた場合、稀に
OBSのウィンドウキャプチャ[FallGuysTools.exe]: Timer_DisplayにFallguysToolsのメインの部分が表示されてしまいます。（OBS画面に2個出ている感じです）
また、[FallGuysTools.exe]: Fall Guys Tools の部分がScoreCounterに置き換わることもあります。
どうにか修正できないでしょうか？それともOBS側のバグですかね？

**Comment by takkun-mint** [comment]
連絡ありがとうございます！
OBSに関しては、説明不足のことがあり申し訳ないです。
OBSのウィンドウキャプチャ機能でToolsの外部表示機能を使う場合は、
初期設定ですとウィンドウの一致優先順位が「タイトルに一致、そうでなければ同じ種類のウィンドウを見つける」
という設定になっています。
このままですと、Toolsの起動するタイミングによって、OBSが誤ったウィンドウを設定してしまう可能性があります。
ですので、ソースプロパティからウィンドウの一致優先順位を「ウィンドウのタイトルに一致する必要があります」
というものに変更していただくと当該問題は解決すると思います！
よろしくお願いします。
![image](https://github.com/takkun-mint/FallGuysTools/assets/117301922/118c8e2e-eb48-48ca-b291-0aa4fff4a0f8)
