### ISSUE TITLE
not matching font on russian language

### ISSUE THREAD

**Issue by repinek** [takkun-mint/FallGuysTools#5]
![image](https://github.com/takkun-mint/FallGuysTools/assets/137826826/efa30f83-f8ed-4498-86d3-3df747799897)
solution: export fall guys russian font from .bundle file

**Comment by repinek** [comment]
original font
![image](https://github.com/takkun-mint/FallGuysTools/assets/137826826/33c72322-ccf9-47ca-a46c-d61c9078273c)

and, please, check my other issue (https://github.com/takkun-mint/FallGuysTools/issues/2) and check my russian translations 
thank

**Comment by takkun-mint** [comment]
> ![image](https://private-user-images.githubusercontent.com/137826826/293402961-efa30f83-f8ed-4498-86d3-3df747799897.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MjQ4MDksIm5iZiI6MTcwNTkyNDUwOSwicGF0aCI6Ii8xMzc4MjY4MjYvMjkzNDAyOTYxLWVmYTMwZjgzLWY4ZWQtNDQ5OC04NmQzLTNkZjc0Nzc5OTg5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQxMTU1MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTMyOTk0NzdiYmRlMzY3MmE4ZGIyZWQzNmM2Mjc0MzYzMWQ1YTE1MWI5YmNhNDE5OTEwNGJkYjMxNzBhNjRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pWpMzSsCrTBDf_b3eqYD9csE_vPTFQj6gYcHrAcfpGo) solution: export fall guys russian font from .bundle file

Thanks for the information!
The original Titan One font does not have any Russian indications,
The fallback font, SweiGothicCJKsc-Bold, is used....
(the game will also use that font if it is not in Titan One).

I'm a bit confused about how to extract the font from the .bundle file.
I would appreciate it if you could tell me how to do it, or give me a URL where the method is described!

**Comment by repinek** [comment]
> > ![image](https://private-user-images.githubusercontent.com/137826826/293402961-efa30f83-f8ed-4498-86d3-3df747799897.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MjQ4MDksIm5iZiI6MTcwNTkyNDUwOSwicGF0aCI6Ii8xMzc4MjY4MjYvMjkzNDAyOTYxLWVmYTMwZjgzLWY4ZWQtNDQ5OC04NmQzLTNkZjc0Nzc5OTg5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQxMTU1MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTMyOTk0NzdiYmRlMzY3MmE4ZGIyZWQzNmM2Mjc0MzYzMWQ1YTE1MWI5YmNhNDE5OTEwNGJkYjMxNzBhNjRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pWpMzSsCrTBDf_b3eqYD9csE_vPTFQj6gYcHrAcfpGo) solution: export fall guys russian font from .bundle file
> 
> Thanks for the information! The original Titan One font does not have any Russian indications, The fallback font, SweiGothicCJKsc-Bold, is used.... (the game will also use that font if it is not in Titan One).
> 
> I'm a bit confused about how to extract the font from the .bundle file. I would appreciate it if you could tell me how to do it, or give me a URL where the method is described!

I think that the game font is stored in the game files, in the .bundle unity files
it storage fallguysfolder\FallGuys_client_game_Data\StreamingAssets\aa~\StandaloneWindows64

I think you can export them using AssetsStudioGUI, or you can ask someone on twitter/reddit

**Comment by takkun-mint** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/137826826/293402961-efa30f83-f8ed-4498-86d3-3df747799897.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MjQ4MDksIm5iZiI6MTcwNTkyNDUwOSwicGF0aCI6Ii8xMzc4MjY4MjYvMjkzNDAyOTYxLWVmYTMwZjgzLWY4ZWQtNDQ5OC04NmQzLTNkZjc0Nzc5OTg5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQxMTU1MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTMyOTk0NzdiYmRlMzY3MmE4ZGIyZWQzNmM2Mjc0MzYzMWQ1YTE1MWI5YmNhNDE5OTEwNGJkYjMxNzBhNjRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pWpMzSsCrTBDf_b3eqYD9csE_vPTFQj6gYcHrAcfpGo) solution: export fall guys russian font from .bundle file
> > 
> > 
> > Thanks for the information! The original Titan One font does not have any Russian indications, The fallback font, SweiGothicCJKsc-Bold, is used.... (the game will also use that font if it is not in Titan One).
> > I'm a bit confused about how to extract the font from the .bundle file. I would appreciate it if you could tell me how to do it, or give me a URL where the method is described!
> 
> I think that the game font is stored in the game files, in the .bundle unity files it storage fallguysfolder\FallGuys_client_game_Data\StreamingAssets\aa~\StandaloneWindows64
> 
> I think you can export them using AssetsStudioGUI, or you can ask someone on twitter/reddit

Thanks for the information!
I was able to extract the files successfully and made the adjustments and completed the application with ver 4.99.52!
Please check it out!

**Comment by repinek** [comment]
Yes, its fixed now, Good job!
![image](https://github.com/takkun-mint/FallGuysTools/assets/137826826/887d5d3e-5358-4018-b324-9019c79f6d53)
