### ISSUE TITLE
broken/wrong text

### ISSUE THREAD

**Issue by repinek** [takkun-mint/FallGuysTools#6]
I played with the unofficial translation of foul gais into Macedonian, and saw this problem
the translation is correct, but either you are importing the wrong line from the content, or something is wrong in your language resources
fallguystools:
![Screenshot_3481](https://github.com/takkun-mint/FallGuysTools/assets/137826826/126d458b-b0c6-4b2e-b89e-135d90ed9afd)
![Screenshot_3482](https://github.com/takkun-mint/FallGuysTools/assets/137826826/eb832415-d7e3-4502-b2fc-e7bc2b15f5b7)
original game:
![Screenshot_3483](https://github.com/takkun-mint/FallGuysTools/assets/137826826/f4e220b6-1a19-4b79-b04f-4f654c023570)

**Comment by repinek** [comment]
> In the meantime, references are made from the contents file for that section. For the "qualified" display, we refer to "ui_overlay_qualified", For "eliminated", "ui_overlay_eliminated" is referenced. As it is unofficial, it is difficult to support even the parts that are not official. We would appreciate it if you could check the settings in the relevant areas to make sure they are correct.

you need to use utf-8 encoding or something like that
srepene patcher (utf-8):
![image](https://github.com/takkun-mint/FallGuysTools/assets/137826826/499c1ab2-9e6d-49b2-800a-2ec0174208f2)

unicode:
![image](https://github.com/takkun-mint/FallGuysTools/assets/137826826/714cb759-db94-4f4e-bf99-9b80a63217ae)

your program shows exactly the same as in the second screenshot
you need to convert unicode to utf-8

(I will take this into account in my translation program, but some other people may have difficulties with this, or if Mediatonic releases Unicode content again)

**Comment by takkun-mint** [comment]
> > In the meantime, references are made from the contents file for that section. For the "qualified" display, we refer to "ui_overlay_qualified", For "eliminated", "ui_overlay_eliminated" is referenced. As it is unofficial, it is difficult to support even the parts that are not official. We would appreciate it if you could check the settings in the relevant areas to make sure they are correct.
> 
> you need to use utf-8 encoding or something like that srepene patcher (utf-8): ![image](https://private-user-images.githubusercontent.com/137826826/300171612-499c1ab2-9e6d-49b2-800a-2ec0174208f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MDgxMjAsIm5iZiI6MTcwNjkwNzgyMCwicGF0aCI6Ii8xMzc4MjY4MjYvMzAwMTcxNjEyLTQ5OWMxYWIyLTllNmQtNDliMi04MDBhLTJlYzAxNzQyMDhmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQyMTAzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzZiM2I0YzBkZTBiMzI2YTYwNzIyMzRiYjU2Y2E0NjVhMWE3ZmEwNWQxMDE2OWM3OTllNjg4YWI2ZGY0YTc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x9jguLkYoAyZYcsKaQzgTkK08P8SwzuyoWZDwoYlTSo)
> 
> unicode: ![image](https://private-user-images.githubusercontent.com/137826826/300171673-714cb759-db94-4f4e-bf99-9b80a63217ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MDgxMjAsIm5iZiI6MTcwNjkwNzgyMCwicGF0aCI6Ii8xMzc4MjY4MjYvMzAwMTcxNjczLTcxNGNiNzU5LWRiOTQtNGY0ZS1iZjk5LTliODBhNjMyMTdhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQyMTAzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ODRkMTBkYzcyNmRhZTM1NTQ2ZTZiYjE3Y2FlOWVkNTBkMDJlOWE5OTE1NTY2MDdjODI0NzNkNzY5YTNjODA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tJVzwqF07TD6kqkrAAJ7NKKHKTQw7d0YwTTp53dSnBw)
> 
> your program shows exactly the same as in the second screenshot you need to convert unicode to utf-8
> 
> (I will take this into account in my translation program, but some other people may have difficulties with this, or if Mediatonic releases Unicode content again)

Thanks for the information.
We have corrected the problem in Ver 4.99.53!

**Comment by repinek** [comment]
good job, thanks for your loyalty
