### ISSUE TITLE
sound for no reason

### ISSUE THREAD

**Issue by repinek** [takkun-mint/FallGuysTools#7]
sound plays when I go to the main menu

https://github.com/takkun-mint/FallGuysTools/assets/137826826/58ea66bd-e457-4641-9f47-ea4bf32b689b

**Comment by takkun-mint** [comment]
When content updates are delivered
a sound effect will be played to notify you.
However, when you set up the Issues
content update had not been delivered when you raised the question, so there is a possibility that this is a bug of some kind.
there is a possibility that this is a bug of some kind.
Although it is tentative, we have fixed the suspicious part of the program in ver 4.99.56.
We hope you will check it out.
