### ISSUE TITLE
デュオのクリエステージでのバグ

### ISSUE THREAD

**Issue by ohsakura0** [takkun-mint/FallGuysTools#8]
デュオで出てくるクリエステージ（自分が確認したのは「RUTA EN LA SELVA」）での問題

・クリア人数が正しく表示されない
![image](https://github.com/takkun-mint/FallGuysTools/assets/127501702/eed0e5b0-b13b-4b63-b6a5-d74f50e8e914)
クリア人数が14になっても終了せず、15人クリア（プレイヤーのうち62.5%がゴール）したところでラウンドが終了しました。（順位確定？）

・ポイントが違う
![image](https://github.com/takkun-mint/FallGuysTools/assets/127501702/3f4dbc5d-455b-4c44-8560-ca3656088fe9)
![image](https://github.com/takkun-mint/FallGuysTools/assets/127501702/15c5e226-a78e-4493-a92f-41794538ab71)
1位24Pt+2位23Pt=47Ptのところを22Pt+21Pt=43Ptとして判定してしまっている問題です。
ラウンド開始前には22人と判定されていますが、
![image](https://github.com/takkun-mint/FallGuysTools/assets/127501702/790bc728-fee4-48dd-9db5-ee949e2385f6)
開始後、元のプレイヤー数は24人と変わり、おそらくこちらの値を基準とすれば正常にポイント取得ができると思われます（12スクワッド突破から2人落ちた）
![image](https://github.com/takkun-mint/FallGuysTools/assets/127501702/9e7e75ef-d51c-4164-9e21-774e0bd287be)

いつもありがとうございます。

**Comment by takkun-mint** [comment]
ご報告ありがとうございます。
こちらに関してなのですが、スクワッドなどに限らず
ラウンド開始前にクライアント側で召喚されていない
プレイヤーがクリア人数による計算に
含まれるときと含まれないときがありまして...。
こちら、ログシステムに差分がないため判断ができないんです...。
今までのテストプレイの結論として、「ブレが激しくどちらとも言えない」
という結果で、一時期はカウントしていたりしていましたが、
現在は「カウントしない」という設定をしております。
問題自体はToolsの開発初期から認識はしているのですが、
ここに関しては、発生頻度が高くないことや差分も取れないため
修正が困難な事案になっています。

スクワッドスコアに関してもログシステムから
スクワッドごとの点数、プレイヤーのスコアすら取得できないため、
（ポイント取得ラウンドは除く）
こちらも上記からTools側ですべて計算・表示を行っているため
ブレが生じているところです。
現状、解決策がなく具体的な話ができず申し訳ないです。
またこちらの問題については引き続きウォッチは続けていますので
なにか変化がありましたらご報告させていただきます。

いつもご利用ありがとうございます。
今後とも宜しくお願いします。
